### ISSUE TITLE
AUR package - Missing dependency

### ISSUE THREAD

**Issue by qw3ry** [meskarune/i3lock-fancy#107]
In the [AUR-package](https://aur.archlinux.org/packages/i3lock-fancy-git/) the dependency on `i3lock-color` is not specified directly. Instead the package depends on `i3lock` which is misleading, especially if you have `i3lock` already installed

**Comment by qw3ry** [comment]
[`i3lock-color`](https://aur.archlinux.org/packages/i3lock-color/) clearly provides `i3lock` _and_ `i3lock-color`. Without knowing to much about the arch dependency system, I assume this means that one can depend on `i3lock-color`.

**Comment by PandorasFox** [comment]
Weird, I guess the maintainer changed the `PKGBUILD` at some point, since that wasn't there the last time I checked.

In that case, yeah, it should be possible to make it a dep. I think the reason before was so that someone could use another fork, since i3lock-fancy doesn't really on _all_ the features in my fork.

**Comment by meskarune** [comment]
At the moment I believe the script can still work using i3lock OR i3lock-color as there is a fallback to regular i3lock.

**Comment by AladW** [comment]
The script will try i3lock if the custom parameters are not accepted or otherwise cause failure: https://github.com/meskarune/i3lock-fancy/blob/master/i3lock-fancy#L124
