### ISSUE TITLE
Grayscale colored circle?

### ISSUE THREAD

**Issue by navdeepio** [meskarune/i3lock-fancy#117]
For me the circle is green colored and displays red pulses while typing? How can I turn it into the grayscale one as shown in the demo?

**Comment by cheapmon** [comment]
Fixed with #118

**Comment by giorgosioak** [comment]
Example of my setup: https://youtu.be/a1bTkxuW2S4

**My circle as is not greyscale as expected!**

$ i3lock-fancy -g , makes background greyscale, not the circle

**Comment by cheapmon** [comment]
@giorgosioak There's likely another issue that prevents the circle being green, even with my fix. PM me @cheapmon on twitter.

**Comment by giorgosioak** [comment]
Oh wait AUR is not updated :/
https://aur.archlinux.org/packages/i3lock-fancy-git/

**Comment by ScreamingTaco** [comment]
I am having this issue as well

**Comment by meskarune** [comment]
There was an update that fixes this now. Please let me know if the latest version is still having color issues.

**Comment by victorbnl** [comment]
I still have this issue

**Comment by ghost** [comment]
I'm also seeing a coloured circle instead of the white/greyscale one as per the [screenshot](https://raw.githubusercontent.com/meskarune/i3lock-fancy/master/screenshot.png).

I installed `i3lock-fancy` via [Debian's stable repo](https://packages.debian.org/bookworm/i3lock-fancy), which seems to depend on `i3lock`, not `i3lock-color`... I'm wondering if that's why. Any colour changes `i3lock-fancy` tries to make to the circle wouldn't work with `i3lock` as it doesn't support them (AFAIK).

So perhaps those having this issue have a similar problem of their distro's version depending on `i3lock`...

**Comment by marie-bnl** [comment]
While it doesn’t fix the issue for this project, as a workaround, you can use i3lock-color. I made a script which runs i3lock with a bunch of arguments. It does other things than setting the right colors, like using my current wallpaper and pausing the notifications, but there you’ll find the right options to change the colors. My circle is grey, red when the password is wrong. Here it is: https://github.com/victorbnl/dotfiles/blob/main/dotfiles/scripts/lockscreen.sh.
