### ISSUE TITLE
 I have any questions about the script autolock

### ISSUE THREAD

**Issue by elhackerlibre** [meskarune/i3lock-fancy#28]
Hello!
I congratulate you on this excellent work!
I have any questions with autolock ?

First question:
the following scripts , which have save path, and name given to the scripts ?
```
[Unit]
Description=Lock the screen automatically after a timeout

[Service]
Type=simple
User=meskarune
Environment=DISPLAY=:0
ExecStart=/usr/bin/xautolock -time 5 -locker /usr/local/bin/lock/lock -detectsleep

[Install]
WantedBy=graphical.target
```
Second question:
I use Archlinux . as I do for the autolock script starts?

I hope you can answer me!
And I again thank you for such a great work...

**Comment by meskarune** [comment]
That script is a unit file used by systemd. They are saved in ```/etc/systemd/system```. I named mine lock.service and then you can start it with ```systemctl start lock```. In order to use that service file you would need xautolocker installed. 

To run the script manually you can just call it like any other program on the system. You could even put it in xinitrc or your window manager's autostart file. I hope this helps you out.

**Comment by meskarune** [comment]
If you are still having problems, please feel free to reopen.
