### ISSUE TITLE
Image doesn't seem to be saved correctly

### ISSUE THREAD

**Issue by clawoflight** [meskarune/i3lock-fancy#3]
It worked briefly though, not sure what the problem is...
This is what I get:
```
composite: unable to open image `lock.png': No such file or directory @ error/blob.c/OpenBlob/2701.
composite: unable to open file `lock.png' @ error/png.c/ReadPNGImage/3913.
composite: missing an image filename `/tmp/i3lock.png' @ error/composite.c/CompositeImageCommand/1616.
```

**Comment by jorenvs** [comment]
The first two errors is about the lock.png, which is in the repository. The problem is that the script only works when you run it from the same directory where the lock.png file is. Simple fix is to change "lock.png" in the script (right after -gravity center) to the absolute path of the file.

The last error is saying it can't find the screenshot, which should have been taken scrot in the line before. Make sure you have scrot and other dependencies installed. You can try verifying this by executing 'scrot /tmp/i3lock.png' and see what happens.

(PS. Just found out about this lockscreen and really loving it, thanks @meskarune.)

**Comment by meskarune** [comment]
Hi @clawoflight, let me know if you still run into problems after making the changes @jorenvs suggests. On my own computer I made a directory `/usr/local/bin/lock` and put all the files in there. Then I use xautolocker to lock my screen automatically after 5 minutes. Really you can change the lock image to any icon you like. Maybe I should look into using the current icon theme's lock icon?

**Comment by Grelek** [comment]
Hello, I just ran into the same problem as @clawoflight and solution by @jorenvs worked like a charm.

BTW, this is really cool script, I like it. :+1:
