### ISSUE TITLE
i3lock doesn't get forked

### ISSUE THREAD

**Issue by Spirotot** [meskarune/i3lock-fancy#39]
i3lock-fancy uses the '-n' parameter (no forking) when exec'ing i3lock. This means that i3lock doesn't fork, which makes it difficult to use in systemd unit files to lock the screen _before_ suspending (i.e. you can't use 'Type=forking' in your unit file). 'Type=oneshot' must be used, which means that the screen will lock _after_ the system resumes from suspend. This is a bit of a security concern, especially since i3lock takes a good 2-4 seconds to actually lock the screen due to the image processing that occurs beforehand (this is on a Skylake i7 with a 4k display.. I'd imagine 1080p screens are approximately 400% faster? So 0.5-2 seconds?).

**Comment by meskarune** [comment]
To be honest, it is far better to use i3lock through your window manager or via a hotkey than through systemd. While it is possible to run using a service file, it behaves in odd ways and no matter what I tried I couldn't get it to work consistently in an expected way.

I currently have my tiling wm start xautolock with the other auto started applications. I think this is the best approach and means locking is tied to your desktop session. Maybe the readme should reflect that?

**Comment by Spirotot** [comment]
That sounds reasonable to me, but I'm not aware of a great way to tie screen-locking to system suspending via the i3 window manager... Well, I do have hotkeys assigned to lock and/or lock+suspend (they just run a bash script that does the appropriate actions). And I also run xautolock to lock the screen after a period of user inactivity. But on laptops specifically, I'd like to be able to just close the lid and have things lock + suspend. Google seemed to reveal that `systemd` was the most frequently recommended way to do that, but I could/should probably spend a bit more time looking at alternative configurations.

**Comment by Arcaena** [comment]
I have my laptop run a different lock script (uses a different lock image that has my name and stuff) that does no image processing at all, since I'd rather not have a blurred screenshot visible at all on resuming from suspend/hibernate.

An alternative is taking the screenshot at and locking with a blank / black background image, doing the processing, then killing that pid and restarting it. There's probably a crap ton wrong with that, but it works. 

I use xautolock with my i3 lock script, and xss lock with my alternative script for on hibernate/suspend/lid close. 

That's just how I do it, but I'm not really sure that there's a decent way to do this. Maybe throwing up a dummy blank lock while image processing, then killing and re-locking?

**Comment by OjasA** [comment]
@Spirotot I am in exactly the same boat as you and just ended up removing the `-n` from this script. It works with systemd as intended.

**Comment by meskarune** [comment]
If you want the screen to lock when you suspend you can use this: https://wiki.archlinux.org/index.php/Power_management#Suspend.2Fresume_service_files

**Comment by AladW** [comment]
Closing as duplicate of #60. See https://github.com/meskarune/i3lock-fancy/pull/60#issuecomment-257538723
