### ISSUE TITLE
Please version i3lock-fancy

### ISSUE THREAD

**Issue by aviau** [meskarune/i3lock-fancy#75]
Hello,

Could you please tag this repository?

I am the Debian Maintainer for this project and tags would help Debian keep up with new releases/bugfixes.

See:
- http://semver.org/

**Comment by AladW** [comment]
Tags imply you have to support both the latest tag and latest commit, which I'm not sure is worth it for a smaller project such as this one.

**Comment by Boruch-Baum** [comment]
Is that really true, that "Tags imply you have to support both the latest tag and latest commit"? Tags are just convenience aliases for commits, and @aviau is correct that if you use tagging to label certain milestone commits (not necessarily each and every commit) in a sequential manner using version numbering, it would make your project more widely available. Git's use of random hashes for labeling commits is otherwise a pain to work with when packaging a project for any distro, not just debian.

If my vote counts for anything, or if this is something up for a vote, I'll second @aviau's suggestion, adding that will in no way require you to treat each tag as fork-point to separately maintained. Is that right @aviau?

**Comment by aviau** [comment]
> Is that right @aviau

Yep. They are just one more tool for me, to keep up with the project.

Sometimes new commits are not worth for me to release, and tags help guiding me with that. Tagging is just one more way to communicate with people using the project, telling them "hey you should update". 

Semver helps me understand what changed, and it gives me information on breaking changes. I can look at the version number without and know whether its a bugfix, feature, or breaking release.

There are some projects I maintain and sometimes what I do is:
 - Commit new features in master
 - Wait a few days
 - I get comments from power users that keep up with master
 - few tweaks or bugfixes
 - tag

**Comment by AladW** [comment]
I'll leave this up to @meskarune.

**Comment by meskarune** [comment]
I don't think using tags would hurt anything. I've just never used them on github before so I need to look into a workflow.

**Comment by AladW** [comment]
It's fairly straightforward, just go to Releases and click "Create a new release". That will create a tag based on a specific commit, as well as an entry displayed in the "Releases" table (including .tar.gz snapshots). You can also add a version variable to the script and update it in a commit where the tag will point to.

**Comment by AladW** [comment]
https://github.com/meskarune/i3lock-fancy/releases/tag/0.1
