### ISSUE TITLE
How does i3lock-fancy interact with slick-greeter?

### ISSUE THREAD

**Issue by baimafeima** [meskarune/i3lock-fancy#95]
I am curious how i3lock-fancy interacts with slick-greeter, the greeter which comes with Solus, the operating system of my choice. Could you explain this process in non-technical terms? And secondly, what would I do if i3lock-fancy locks a user out by causing problems with the default screen lock mechanisms at place in various operating systems?

**Comment by patrick96** [comment]
i3lock-fancy, is only a wrapper for [i3lock](https://github.com/i3/i3lock). You'd probably be better of, asking that question over there. But I don't think i3lock interacts with the greeter or display manager at all. If you are locked out, you can switch to another tty by pressing `Ctrl` + `Alt` + `F2` (or any other F-key), logging in there and manually killing the i3lock process

**Comment by AladW** [comment]
I think the above answers it pretty well. Thanks.

**Comment by chrjguill** [comment]
Yeah, so all that the greeter (or display manager) does is manage logging in + starting your x session and stuff, with your desired window manager/DE/etc. It's also run by the system, typically with fairly limited permissions/access (I think actually as `nobody:nogroup`. There's a handful of reasons why, but basically, since no one is logged in, it can crash and it'll just get restarted by your init process. It can also safely crash since it means that it won't give you access to some user's session.

i3lock is run under your user. When you run it, it grabs the x server and puts a window on top of everything to hide what's going on, as well as grabbing the keyboard/mouse so that no input goes to any user processes. It's pretty important that you can't crash it, since that would just get you access to the session that ran the locker.

They're pretty different things.

**Comment by baimafeima** [comment]
Thanks a lot for the comments. 

> It's pretty important that you can't crash it, since that would just get you access to the session that ran the locker.

@chrjguill This sounds interesting. Would you mind explaining this a bit more in detail? Not that I plan to find a way to crash it but I'd like to understand in what way this could potentially compromise the security of a computer.

**Comment by chrjguill** [comment]
So basically, the screenlocker is just run by your user and it grabs everything. If it crashes, then the display and inputs will return to normal, as if you unlocked it successfully.

It basically functions like a game that grabs the display and all inputs, but somewhat more aggressively.
